// GENERATED FILE - DO NOT EDIT.
// Generated by tool/generate-lucide-icons.mjs from lucide-static.

part of 'lucide_icon.dart';

List<Component>? _buildLucideNodes(String name) {
  switch (name) {
    case 'circle-dot':
      return [
        circle(cx: '12', cy: '12', r: '10', []),
        circle(cx: '12', cy: '12', r: '1', []),
      ];
    case 'layout-dashboard':
      return [
        rect(width: '7', height: '9', x: '3', y: '3', rx: '1', []),
        rect(width: '7', height: '5', x: '14', y: '3', rx: '1', []),
        rect(width: '7', height: '9', x: '14', y: '12', rx: '1', []),
        rect(width: '7', height: '5', x: '3', y: '16', rx: '1', []),
      ];
    case 'logs':
      return [
        path(d: 'M3 5h1', []),
        path(d: 'M3 12h1', []),
        path(d: 'M3 19h1', []),
        path(d: 'M8 5h1', []),
        path(d: 'M8 12h1', []),
        path(d: 'M8 19h1', []),
        path(d: 'M13 5h8', []),
        path(d: 'M13 12h8', []),
        path(d: 'M13 19h8', []),
      ];
    case 'refresh-cw':
      return [
        path(d: 'M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8', []),
        path(d: 'M21 3v5h-5', []),
        path(d: 'M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16', []),
        path(d: 'M8 16H3v5', []),
      ];
    case 'send-horizontal':
      return [
        path(d: 'M3.714 3.048a.498.498 0 0 0-.683.627l2.843 7.627a2 2 0 0 1 0 1.396l-2.842 7.627a.498.498 0 0 0 .682.627l18-8.5a.5.5 0 0 0 0-.904z', []),
        path(d: 'M6 12h16', []),
      ];
    case 'settings':
      return [
        path(d: 'M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915', []),
        circle(cx: '12', cy: '12', r: '3', []),
      ];
    case 'sun-moon':
      return [
        path(d: 'M12 2v2', []),
        path(d: 'M14.837 16.385a6 6 0 1 1-7.223-7.222c.624-.147.97.66.715 1.248a4 4 0 0 0 5.26 5.259c.589-.255 1.396.09 1.248.715', []),
        path(d: 'M16 12a4 4 0 0 0-4-4', []),
        path(d: 'm19 5-1.256 1.256', []),
        path(d: 'M20 12h2', []),
      ];
    case 'x':
      return [
        path(d: 'M18 6 6 18', []),
        path(d: 'm6 6 12 12', []),
      ];
    default:
      return null;
  }
}
